apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: coredns
  labels:
    app.kubernetes.io/name: coredns
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: coredns
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
      nodePort: 30053
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
      nodePort: 30054
