apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pv-shared-photos.yaml
  - pvc-config.yaml
  - pvc-photos.yaml
  - secret-icloud-credentials.yaml
  - configmap-icloudpd.yaml
  - serviceaccount.yaml
  - cronjob.yaml
