apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: immich
spec:
  template:
    spec:
      containers:
      - name: immich
        volumeMounts:
        - name: icloud-import
          mountPath: /external/icloud
          readOnly: true
      volumes:
      - name: icloud-import
        hostPath:
          path: /var/mnt/icloud-photos
          type: Directory
