apiVersion: v1
kind: Service
metadata:
  name: admin-pod-ssh
  namespace: admin-pod
spec:
  type: NodePort
  selector:
    app: admin-pod
  ports:
  - port: 22
    targetPort: 22
    nodePort: 30022
    protocol: TCP
    name: ssh
